# Generated by Django 4.2.4 on 2023-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
